name: Fetch developers.json from Previous and Current Commit

on:
  push:
    branches:
      - main  # Change this to your branch name if different

jobs:
  fetch-files:
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
        with:
          fetch-depth: 2
        
      - name: Get previous commit hash
        id: get_previous_commit
        run: echo "prev_commit=$(git rev-parse HEAD^1)" >> $GITHUB_ENV
        
      - name: Get current commit hash
        id: get_current_commit
        run: echo "curr_commit=$(git rev-parse HEAD)" >> $GITHUB_ENV
        
      - name: Fetch developers.json from previous commit
        id: fetch_prev_developers
        run: |
          git show ${{ env.prev_commit }}:src/tests/test-bundle/developers.json > prev_developers.json
          cat prev_developers.json
          
      - name: Fetch developers.json from current commit
        id: fetch_curr_developers.json
        run: |
          git show ${{ env.curr_commit }}:src/tests/test-bundle/developers.json > curr_developers.json
          cat curr_developers.json
          
      - name: Print variables
        run: |
          echo "Previous developers.json content:"
          cat prev_developers.json
          echo "Current developers.json content:"
          cat curr_developers.json




